location /api/v1/academic/ {
    limit_req zone=api_limit burst=20 nodelay;
    if ($http_authorization = "") { return 401; }
    set $academic_api http://educk-academic-api:8082;
    proxy_pass $academic_api;
    proxy_set_header X-Correlation-Id $req_correlation_id;
    include /etc/nginx/snippets/headers.conf;
}
