location /api/v1/attendance/ {
    limit_req zone=api_limit burst=20 nodelay;
    if ($http_authorization = "") { return 401; }
    set $attendance_api http://educk-attendance-api:8083;
    proxy_pass $attendance_api;
    proxy_set_header X-Correlation-Id $req_correlation_id;
    include /etc/nginx/snippets/headers.conf;
}
