name: educk-api-gateway

services:
  api-gateway:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports: ["8000:8000"]
    networks: [platform]

networks:
  platform:
    name: platform
    external: true
