worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    log_format json_log escape=json '{'
        '"timestamp":"$time_iso8601",'
        '"correlationId":"$http_x_correlation_id",'
        '"remoteAddr":"$remote_addr",'
        '"request":"$request",'
        '"status":$status,'
        '"bodyBytesSent":$body_bytes_sent,'
        '"userAgent":"$http_user_agent"'
    '}';
    access_log /var/log/nginx/access.log json_log;
    
    client_max_body_size 10M;
    sendfile on;
    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf;
}
