server {
    listen 8080;
    server_name localhost;

    include /etc/nginx/snippets/headers.conf;

    error_page 401 @401_json;
    error_page 404 @404_json;
    error_page 429 @429_json;
    error_page 503 @503_json;

    location @401_json {
        default_type application/json;
        return 401 '{"error":"UNAUTHORIZED","traceId":"$req_correlation_id"}';
    }
    location @404_json {
        default_type application/json;
        return 404 '{"error":"NOT_FOUND","traceId":"$req_correlation_id"}';
    }
    location @429_json {
        default_type application/json;
        return 429 '{"error":"TOO_MANY_REQUESTS","traceId":"$req_correlation_id"}';
    }
    location @503_json {
        default_type application/json;
        return 503 '{"error":"SERVICE_UNAVAILABLE","traceId":"$req_correlation_id"}';
    }

    include /etc/nginx/routes/*.conf;
}
